library(shiny)
library(readr)
library(DT)
library(visNetwork)
library(dplyr)
library(stringr)
library(igraph)
library(shinydashboard)
library(here)

print(R.utils::sourceDirectory(here('shiny', 'functions')))
print(R.utils::sourceDirectory(here('shiny', 'modules')))
